### PR TITLE
Adds some controller tests

### PR DESCRIPTION
**Pull request by afred**
- Adds controller specs for:
  - GET /stores
  - GET /stores/:store_name
  - GET /stores/:store_name/files
  - GET /stores/:store_name/files/:id
- Adds validation (required + unique) for Store#name.
- Uses FactoryGirl gem, and adds factories for Store and MediaFiles.
- Removes some stuff that we probably don't need.
- Renames files containing routing specs, just for more clarity.
- Adds pry-bybug gem.

### CODE REVIEW

**Comment by afred** [comment]
@randalldfloyd review?

**Comment by randalldfloyd** [comment]
@afred Just curious, are you able to get real file responses back as-is? When I test the routes they are still trying to treat file extensions as format disambiguators.

**Comment by afred** [comment]
@randalldfloyd No, i haven't created a test for testing filenames with extensions yet.

**Comment by randalldfloyd** [comment]
@afred Ok, I was trying to put the cart before the horse I guess. I pulled down the branch and was trying to exercise routes but that will come as the route tests are developed.

**Comment by afred** [comment]
@randalldfloyd yeah, my process has been thus...
1. run `rake routes`
2. check to see if all the desired routes are covered.
3. for each route, make sure there is a routing test to ensure the mock storage proxy responds to the route.
4. for each route, look to see what controller action it is tied to, and then write a spec for that controller action that checks the JSON response

As the commit message points out, I've got a handful of the controller actions tested. But there are a few more.

**Pull request merged**
